apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysite
  namespace: default
  annotations:
   kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: reg.anthony.bible
    http:
      paths:
      - path: /
        backend:
          serviceName: registration-service
          servicePort: 80
  tls:
    - hosts:
      - reg.anthony.bible
      secretName: reg.anthony.bible-cert
